### ISSUE TITLE
Segmentation fault during piece placement

### ISSUE THREAD

**Issue by MatthewMateusz** [tjunruh/Stratego#15]
I have not pined down where the issue is but a segmentation fault occurred during piece placement:
![image](https://github.com/tjunruh/Stratego/assets/13612352/281e0186-32f7-4edc-a2cf-c53f5b96136b)

What happened is I hit a key that is not a piece placement.

**Platform**: Linux

If I have time, I will investigate this issue bit and try to narrow it down.

**Comment by tjunruh** [comment]
This issue appears to be fixed now since the application is using ASCII_Board_Game_Engine. I'll close this issue.
