### ISSUE TITLE
How do you play?

### ISSUE THREAD

**Issue by NonlinearFruit** [tjunruh/Stratego#2]
I got this far and I can use the arrow keys to move the `( )` around. How do I place pieces?

![image](https://user-images.githubusercontent.com/6962125/230649183-05526152-31ae-4f94-aaff-595391975335.png)

**Comment by tjunruh** [comment]
You have to be on the bottom half of the board. Press the number or letter of the piece to place the piece. I should probably add a way to display game controls and rules within the program.

**Comment by NonlinearFruit** [comment]
Ooh, ok. I was trying all sorts of stuff, but I was on the top half of the board. Moving to the bottom half of the board fixed it 😂

**Comment by NonlinearFruit** [comment]
After you have selected a piece (with enter) and picked a direction (with an arrow key), is there a way to escape and select a different piece?

**Comment by tjunruh** [comment]
Yes, you can press 'q' to unselect the piece.

**Comment by tjunruh** [comment]
There is now a controls menu you can display by pressing 'h'.

**Comment by NonlinearFruit** [comment]
Nice! That is helpful
